export const CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME';
export const CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY';
export const CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET';

export const SMTP_HOST = 'SMTP_HOST';
export const SMTP_PORT = 'SMTP_PORT';
export const SMTP_USER = 'SMTP_USER';
export const SMTP_PASSWORD = 'SMTP_PASSWORD';
