openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Management API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing personal contacts with authentication
tags:
  - name: Contacts
    description: Operations about contacts
  - name: Auth
    description: Auth operations
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-3-4hc6.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{contacts}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contacts}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contacts}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
